name = "creator-tool-hub"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

# Build command is configured in Cloudflare Pages dashboard to include:
# NEXT_PUBLIC_WORKER_API_URL=https://creator-tool-hub.techfren.workers.dev npm run pages:build

[vars]
NEXT_PUBLIC_WORKER_API_URL = "https://creator-tool-hub.techfren.workers.dev"
WORKER_BASE_URL = "https://creator-tool-hub.techfren.workers.dev"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NEXT_PUBLIC_WORKER_API_URL = "https://creator-tool-hub.techfren.workers.dev"
WORKER_BASE_URL = "https://creator-tool-hub.techfren.workers.dev"

[env.preview]
compatibility_flags = ["nodejs_compat"]
